(ns gui.globals)

(def init-size 800)
(def task-filter (atom ""))
(def input-string (atom (atom "")))
(def invert-colors (atom true))
(def prio-threshold (atom 0.0))
(def link-labels (atom false))
(def concept-filter (atom "_DELETE_ME_"))
(def inputstr (atom ""))
(def speed (atom "slow"))